### PR TITLE
Hide Community Portal subcategories css

### PR DESCRIPTION
**Pull request by nukeador**

### CODE REVIEW

**Comment by the-smooth-operator** [comment]
looks good to me

**Comment by nukeador** [comment]
Who can merge this?

**Comment by the-smooth-operator** [comment]
I don't have merge rights. @LeoMcA could you please grant me write access to this repo?

**Comment by LeoMcA** [comment]
@The-smooth-operator I don't seem to have write access either, I think you'll need to ask one of the mozilla github admins.

**Pull request merged**
